/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Canyon.glb 
*/

import React, { useRef } from 'react'
import { useSnapshot } from "valtio"

import { useGLTF } from '@react-three/drei'
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';


export function Canyon(props) {
  const { nodes, materials } = useGLTF('models/Canyon.glb')
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)

  const canvasRef = useRef(document.createElement("canvas"));
  const textureRef = useRef();
  const context = useRef(canvasRef.current.getContext("2d"));
console.log()

  canvasRef.current.width = 1600;
  canvasRef.current.height = 1600;

  let ctx = context.current;

  ctx.globalCompositeOperation = "hue";

  const img = document.getElementById(`overlay${overlay}`);

  if (img.complete) {
    ctx.drawImage(img, 0, 0);
    if (snap1.base.BaseMtl !== "none") {
      if(overlay!==1){
      ctx.fillStyle = snap1.base.BaseMtl;
      ctx.fillRect(0, 0, 1600, 1600);
      }
    }


    if (textureRef.current) {
      textureRef.current.needsUpdate = true;
    }
  }

  else {
    img.onload = function () {
      ctx.drawImage(img, 0, 0);
      if (snap1.base.BaseMtl !== "none") {
        if(overlay!==1){
        ctx.fillStyle = snap1.base.BaseMtl;
        ctx.fillRect(0, 0, 1600, 1600);
        }
      }
      


      if (textureRef.current) {
        textureRef.current.needsUpdate = true;
      }
    }
  }
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.416, -14.001]} rotation={[Math.PI / 2, 0, 0]} scale={0.046}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group position={[0.002, 2219.437, 1009.466]} scale={10}>
            <mesh geometry={nodes.black_01_black_0.geometry} material={materials.black} position={[0, 0.047, 0.015]} />
          </group>
          <mesh geometry={nodes.black_03_black_0.geometry} material={materials.black} position={[-8.597, 136.784, 599.219]} scale={10} />
          <group position={[0.002, 355.519, 1402.226]} scale={10}>
            <mesh geometry={nodes.black_04_black_0.geometry} material={materials.black} position={[0, -0.213, -0.092]} />
          </group>
          <group position={[0.002, 662.636, 1432.165]} scale={10}>
            <mesh geometry={nodes.black_05_black_0.geometry} material={materials.black} position={[0, 0.007, 0.019]} />
          </group>
          <group position={[0.002, -1155.608, 1204.652]} scale={10}>
            <mesh geometry={nodes.black_06_black_0.geometry} material={materials.black} position={[0, -0.003, -0.008]} />
          </group>
          <group position={[0, -850.375, 1392.416]} scale={10}>
            <mesh geometry={nodes.black_07_black_0.geometry} material={materials.black} position={[0, -0.011, 0]} />
          </group>
          <group position={[0, -2151.161, 916.473]} scale={10}>
            <mesh geometry={nodes.black_09_black_0.geometry} material={materials.black} position={[0, 0.133, -0.005]} />
          </group>
          <group position={[0, -2241.459, 777.563]} scale={10}>
            <mesh geometry={nodes.black_matt_01_black_matt_0.geometry} material={materials.black_matt} position={[0, -0.002, 0.012]} />
          </group>
          <mesh geometry={nodes.black_matt_02_black_matt_0.geometry} material={materials.black_matt} position={[-8.598, 22.689, 536.934]} scale={10} />
          <group position={[0, 2280.664, 587.811]} scale={10}>
            <mesh geometry={nodes.black_matt_03_black_matt_0.geometry} material={materials.black_matt} position={[0, -0.039, 0]} />
          </group>
          <group position={[768.033, 1373.972, 393.15]} scale={10}>
            <mesh geometry={nodes.black_matt_04_black_matt_0.geometry} material={materials.black_matt} position={[0, 0.341, 0.214]} />
          </group>
          <group position={[801.056, 1385.876, 394.141]} scale={10}>
            <mesh geometry={nodes.black_matt_06_black_matt_0.geometry} material={materials.black_matt} position={[0, 0.542, 0.427]} />
          </group>
          <group position={[0.001, 1502.064, 433.162]} scale={10}>
            <mesh geometry={nodes.black_matt_08_black_matt_0.geometry} material={materials.black_matt} position={[0, -0.029, -0.001]} />
          </group>
          <group position={[0.002, 1511.697, 1238.57]} scale={10}>
            <mesh geometry={nodes.black_matt_09_black_matt_0.geometry} material={materials.black_matt} position={[0, 0.032, -0.023]} />
          </group>
          <group position={[241.637, -1590.63, 366.844]} scale={10}>
            <mesh geometry={nodes.black_matt_14_black_matt_0.geometry} material={materials.black_matt} position={[0.04, 0, -0.042]} />
          </group>
          <group position={[231.156, -1562.8, 618.458]} scale={10}>
            <mesh geometry={nodes.black_matt_15_black_matt_0.geometry} material={materials.black_matt} position={[0, 0, -0.006]} />
          </group>
          <mesh geometry={nodes.black_matt_19_black_matt_0.geometry} material={materials.black_matt} position={[-8.599, -1536.926, 723.948]} scale={10} />
          <group position={[-8.596, -1536.886, 865.878]} scale={10}>
            <mesh geometry={nodes.black_matt_20_black_matt_0.geometry} material={materials.black_matt} position={[0, 0, 0.058]} />
          </group>
          <group position={[739.386, -1532.116, 365.975]} scale={10}>
            <mesh geometry={nodes.black_matt_22_black_matt_0.geometry} material={materials.black_matt} position={[0, 0, 0.212]} />
          </group>
          <group position={[250.823, -1497.899, 365.877]} scale={10}>
            <mesh geometry={nodes.black_matt_23_black_matt_0.geometry} material={materials.black_matt} position={[0, -0.007, 0]} />
          </group>
          <group position={[761.72, -1420.639, 391.725]} scale={10}>
            <mesh geometry={nodes.black_matt_25_black_matt_0.geometry} material={materials.black_matt} position={[0, 0.341, 0.214]} />
          </group>
          <group position={[794.743, -1408.735, 392.716]} scale={10}>
            <mesh geometry={nodes.black_matt_27_black_matt_0.geometry} material={materials.black_matt} position={[0, 0.542, 0.427]} />
          </group>
          <mesh geometry={nodes.black_matt_28_black_matt_0.geometry} material={materials.black_matt} position={[-8.599, -1391.69, 538.135]} scale={10} />
          <group position={[0, 2299.604, 537.458]} scale={10}>
            <mesh geometry={nodes.black_matt_31_black_matt_0.geometry} material={materials.black_matt} position={[0, 0.328, 0]} />
          </group>
          <group position={[0.001, 2301.515, 1124.851]} scale={10}>
            <mesh geometry={nodes.black_matt_32_black_matt_0.geometry} material={materials.black_matt} position={[0, 0.002, 0]} />
          </group>
          <group position={[0.002, -131.022, 1254.146]} scale={10}>
            <mesh geometry={nodes.black_matt_33_black_matt_0.geometry} material={materials.black_matt} position={[0, 0, -0.013]} />
          </group>
          <group position={[0.002, 41.765, 1425.606]} scale={10}>
            <mesh geometry={nodes.black_matt_34_black_matt_0.geometry} material={materials.black_matt} position={[0, -0.044, 0.007]} />
          </group>
          <group position={[165.14, 1168.435, 365.692]} scale={10}>
            <mesh geometry={nodes.black_matt_36_black_matt_0.geometry} material={materials.black_matt} position={[0, 0.011, 0]} />
          </group>
          <group position={[745.699, 1262.494, 367.4]} scale={10}>
            <mesh geometry={nodes.black_matt_40_black_matt_0.geometry} material={materials.black_matt} position={[0, 0, 0.212]} />
          </group>
          <group position={[139.156, 1263.008, 364.938]} scale={10}>
            <mesh geometry={nodes.black_matt_41_black_matt_0.geometry} material={materials.black_matt} position={[0.131, 0, -0.057]} />
          </group>
          <group position={[0.002, 78.823, 1636.897]} scale={10}>
            <mesh geometry={nodes.black_matt_43_black_matt_0.geometry} material={materials.black_matt} position={[0, 0.012, 0.036]} />
          </group>
          <group position={[-8.598, 124.725, 423.823]} scale={10}>
            <mesh geometry={nodes.black_matt_44_black_matt_0.geometry} material={materials.black_matt} position={[0, -0.001, 0]} />
          </group>
          <group position={[-440.857, 174.395, 571.146]} scale={10}>
            <mesh geometry={nodes.black_matt_45_black_matt_0.geometry} material={materials.black_matt} position={[0.076, 0.037, -0.084]} />
          </group>
          <group position={[1.146, 515.048, 1776.548]} scale={10}>
            <mesh geometry={nodes.black_matt_46_black_matt_0.geometry} material={materials.black_matt} position={[0, -0.157, 0.002]} />
          </group>
          <group position={[0.002, 625.536, 1641.314]} scale={10}>
            <mesh geometry={nodes.black_matt_48_black_matt_0.geometry} material={materials.black_matt} position={[0, 0.03, 0.003]} />
          </group>
          <group position={[-8.593, 752.61, 503.805]} scale={10}>
            <mesh geometry={nodes.black_matt_51_black_matt_0.geometry} material={materials.black_matt} position={[0, 0.014, -0.002]} />
          </group>
          <group position={[0.002, -1030.726, 448.744]} scale={10}>
            <mesh geometry={nodes.black_matt_55_black_matt_0.geometry} material={materials.black_matt} position={[0, -0.009, 0]} />
          </group>
          <group position={[0.002, -1030.214, 448.38]} scale={10}>
            <mesh geometry={nodes.black_matt_56_black_matt_0.geometry} material={materials.black_matt} position={[0, -0.009, 0]} />
          </group>
          <mesh geometry={nodes.black_matt_57_black_matt_0.geometry} material={materials.black_matt} position={[250.919, -799.375, 465.374]} scale={10} />
          <group position={[0, -787.35, 1249.22]} scale={10}>
            <mesh geometry={nodes.black_matt_58_black_matt_0.geometry} material={materials.black_matt} position={[0, 0.027, -0.079]} />
          </group>
          <group position={[0, -857.999, 1259.686]} scale={10}>
            <mesh geometry={nodes.black_matt_61_black_matt_0.geometry} material={materials.black_matt} position={[0, 0, 0.43]} />
          </group>
          <group position={[0, -2182.897, 467.699]} scale={10}>
            <mesh geometry={nodes.black_matt_62_black_matt_0.geometry} material={materials.black_matt} position={[0, -0.031, 0]} />
          </group>
          <group position={[0, -2336.927, 1087.659]} scale={10}>
            <mesh geometry={nodes.black_matt_65_black_matt_0.geometry} material={materials.black_matt} position={[0, -0.023, -0.01]} />
          </group>
          <group position={[-0.582, -2318.09, 903.053]} scale={10}>
            <mesh geometry={nodes.black_matt_66_black_matt_0.geometry} material={materials.black_matt} position={[0.007, 0, 0]} />
          </group>
          <group position={[-0.282, -2282.154, 755]} scale={10}>
            <mesh geometry={nodes.black_matt_67_black_matt_0.geometry} material={materials.black_matt} position={[0.048, -0.001, -0.017]} />
          </group>
          <mesh geometry={nodes.black_matt_68_black_matt_0.geometry} material={materials.black_matt} position={[-0.187, -2281.387, 903.98]} scale={10} />
          <group position={[0, -2257.608, 588.305]} scale={10}>
            <mesh geometry={nodes.black_matt_69_black_matt_0.geometry} material={materials.black_matt} position={[0, 0.005, -0.001]} />
          </group>
          <group position={[0, -2241.213, 579.878]} scale={10}>
            <mesh geometry={nodes.black_matt_70_black_matt_0.geometry} material={materials.black_matt} position={[0, -0.024, -0.001]} />
          </group>
          <group position={[0, -2226.564, 578.72]} scale={10}>
            <mesh geometry={nodes.black_matt_71_black_matt_0.geometry} material={materials.black_matt} position={[0, -0.027, -0.014]} />
          </group>
          <mesh geometry={nodes.black_matt_76_black_matt_0.geometry} material={materials.black_matt} position={[-8.599, -667.237, 498.376]} scale={10} />
          <mesh geometry={nodes.black_matt_77_black_matt_0.geometry} material={materials.black_matt} position={[173.061, -590.196, 491.336]} scale={10} />
          <mesh geometry={nodes.black_matt_78_black_matt_0.geometry} material={materials.black_matt} position={[-8.597, -541.743, 443.811]} scale={10} />
          <group position={[0.002, -450.342, 1423.733]} scale={10}>
            <mesh geometry={nodes.black_matt_79_black_matt_0.geometry} material={materials.black_matt} position={[0, 0.056, 0.01]} />
          </group>
          <group position={[744.903, 1261.474, 368.092]} scale={10}>
            <mesh geometry={nodes.black_shiny_01_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.077, 0, 0.064]} />
          </group>
          <group position={[-744.903, 1261.474, 368.092]} scale={10}>
            <mesh geometry={nodes.black_shiny_02_black_shiny_0.geometry} material={materials.black_shiny} position={[0.077, 0, 0.064]} />
          </group>
          <group position={[744.903, -1532.116, 368.092]} scale={10}>
            <mesh geometry={nodes.black_shiny_03_black_shiny_0.geometry} material={materials.black_shiny} position={[-0.077, 0, 0.064]} />
          </group>
          <group position={[-744.903, -1532.116, 368.092]} scale={10}>
            <mesh geometry={nodes.black_shiny_04_black_shiny_0.geometry} material={materials.black_shiny} position={[0.077, 0, 0.064]} />
          </group>
          <group position={[0, -760.118, 1058.917]} scale={10}>
            <group position={[0, -0.027, 0.043]}>
            <mesh geometry={nodes.Body.geometry}>
        <meshStandardMaterial {...materials.BaseMtl} color={overlay==1 || overlay==13 ? (snap1.base.BaseMtl!=="none" ? snap1.base.BaseMtl : 0xffffff) : 0xffffff}>
          <canvasTexture
            flipY={false}
            wrapS={1000}
            wrapT={1000}
            colorSpace='srgb'
            ref={textureRef}
            attach="map"
            image={canvasRef.current}
          />
        </meshStandardMaterial>
      </mesh>
            </group>
          </group>
          <group position={[0, -98.175, 1060.566]} scale={10}>
            <mesh geometry={nodes.body_04_body_0.geometry} material={materials.body} position={[0, -0.003, -0.006]} />
          </group>
          <group position={[0, -840.093, 1272.978]} scale={10}>
            <mesh geometry={nodes.body_05_body_0.geometry} material={materials.body} position={[0, 0.009, 0.059]} />
          </group>
          <mesh geometry={nodes.brakes1_02_brakes1_0.geometry} material={materials.brakes1} position={[761.171, -1541.898, 365.898]} scale={10} />
          <mesh geometry={nodes.brakes1_04_brakes1_0.geometry} material={materials.brakes1} position={[767.483, 1252.712, 367.323]} scale={10} />
          <group position={[0.035, -2333.18, 902.884]} scale={10}>
            <mesh geometry={nodes.chrome_01_chrome_0.geometry} material={materials.chrome} position={[0.002, -0.005, 0]} />
          </group>
          <group position={[0, -2136.366, 914.601]} scale={10}>
            <mesh geometry={nodes.chrome_02_chrome_0.geometry} material={materials.chrome} position={[0, 0.041, -0.039]} />
          </group>
          <group position={[-0.075, 2313.463, 1022.014]} scale={10}>
            <mesh geometry={nodes.chrome_03_chrome_0.geometry} material={materials.chrome} position={[0.001, -0.006, 0]} />
          </group>
          <group position={[0, 2228.74, 1011.82]} scale={10}>
            <mesh geometry={nodes.chrome_05_chrome_0.geometry} material={materials.chrome} position={[0, 0.021, -0.005]} />
          </group>
          <group position={[0, 2242.621, 997.518]} scale={10}>
            <mesh geometry={nodes.chrome_06_chrome_0.geometry} material={materials.chrome} position={[0, 0.007, 0]} />
          </group>
          <group position={[841.524, -1534.319, 367.179]} scale={10}>
            <mesh geometry={nodes.chrome_07_chrome_0.geometry} material={materials.chrome} position={[0.017, 0, 0]} />
          </group>
          <group position={[-841.524, -1534.319, 367.179]} scale={10}>
            <mesh geometry={nodes.chrome_08_chrome_0.geometry} material={materials.chrome} position={[-0.017, 0, 0]} />
          </group>
          <group position={[552.829, 2286.886, 729.772]} scale={10}>
            <mesh geometry={nodes.chrome_13_chrome_0.geometry} material={materials.chrome} position={[-0.02, 0, 0.002]} />
          </group>
          <group position={[-515.699, 2290.456, 725.563]} scale={10}>
            <mesh geometry={nodes.chrome_14_chrome_0.geometry} material={materials.chrome} position={[-0.001, -0.001, 0]} />
          </group>
          <group position={[0.001, 2312.126, 929.016]} scale={10}>
            <mesh geometry={nodes.chrome_15_chrome_0.geometry} material={materials.chrome} position={[0.003, -0.034, -0.001]} />
          </group>
          <group position={[841.524, 1259.272, 367.179]} scale={10}>
            <mesh geometry={nodes.chrome_16_chrome_0.geometry} material={materials.chrome} position={[0.017, 0, 0]} />
          </group>
          <group position={[-841.524, 1259.272, 367.179]} scale={10}>
            <mesh geometry={nodes.chrome_17_chrome_0.geometry} material={materials.chrome} position={[-0.017, 0, 0]} />
          </group>
          <group position={[0.001, 632.523, 1641.285]} scale={10}>
            <mesh geometry={nodes.chrome_20_chrome_0.geometry} material={materials.chrome} position={[0, 0.04, 0.006]} />
          </group>
          <group position={[-827.355, -832.99, 718.168]} scale={10}>
            <mesh geometry={nodes.chrome_23_chrome_0.geometry} material={materials.chrome} position={[-0.018, 0, 0]} />
          </group>
          <mesh geometry={nodes.chrome_24_chrome_0.geometry} material={materials.chrome} position={[830.823, -794.123, 722.314]} scale={10} />
          <group position={[0, -2034.132, 916.964]} scale={10}>
            <mesh geometry={nodes.chrome_26_chrome_0.geometry} material={materials.chrome} position={[0, -0.053, 0]} />
          </group>
          <mesh geometry={nodes.chrome_27_chrome_0.geometry} material={materials.chrome} position={[-830.812, -783.569, 722.643]} scale={10} />
          <group position={[0, -2172.5, 585.382]} scale={10}>
            <mesh geometry={nodes.chrome_30_chrome_0.geometry} material={materials.chrome} position={[0, -0.006, -0.031]} />
          </group>
          <group position={[0.002, 678.124, 1432.165]} scale={10}>
            <mesh geometry={nodes.d_glass_01_d_glass_0.geometry} material={materials.d_glass} position={[0, 0.007, 0.019]} />
          </group>
          <group position={[0, -855.472, 1392.416]} scale={10}>
            <mesh geometry={nodes.d_glass_02_d_glass_0.geometry} material={materials.d_glass} position={[0, -0.012, 0]} />
          </group>
          <group position={[0.002, -158.643, 1370.068]} scale={10}>
            <mesh geometry={nodes.d_glass_03_d_glass_0.geometry} material={materials.d_glass} position={[0, -0.354, 0.014]} />
          </group>
          <group position={[0, 2287.073, 998.075]} scale={10}>
            <mesh geometry={nodes.glass_01_glass_0.geometry} material={materials.glass} />
            <mesh geometry={nodes.glass_01_glass_0001.geometry} material={materials.glass} />
          </group>
          <group position={[0.001, 2225.837, 1009.466]} scale={10}>
            <mesh geometry={nodes.glass_03_glass_0.geometry} material={materials.glass} position={[0, 0.009, -0.002]} />
          </group>
          <group position={[0, -2214.68, 585.316]} scale={10}>
            <mesh geometry={nodes.glass_08_glass_0.geometry} material={materials.glass} position={[0, -0.003, -0.025]} />
          </group>
          <mesh geometry={nodes.glass_09_glass_0.geometry} material={materials.glass} position={[0, -2176.981, 930.252]} scale={10} />
          <group position={[0, -2148.869, 916.13]} scale={10}>
            <mesh geometry={nodes.glass_10_glass_0.geometry} material={materials.glass} position={[0, 0.118, 0.005]} />
          </group>
          <group position={[0, -197.268, 1109.529]} scale={10}>
            <mesh geometry={nodes.interior_04_interior_0.geometry} material={materials.interior} position={[0, -0.376, 0.042]} />
          </group>
          <group position={[-0.79, -2076.953, 928.768]} scale={10}>
            <mesh geometry={nodes.o_glass_01_o_glass_0.geometry} material={materials.o_glass} position={[0.046, -0.037, -0.003]} />
          </group>
          <mesh geometry={nodes.plate_01_plate_0.geometry} material={materials.plate} position={[0, 2310.333, 607.702]} scale={10} />
          <group position={[0, 2234.469, 1012.054]} scale={10}>
            <mesh geometry={nodes.r_glass_01_r_glass_0.geometry} material={materials.r_glass} position={[0, 0.084, 0.004]} />
          </group>
          <mesh geometry={nodes.r_glass_02_r_glass_0.geometry} material={materials.r_glass} position={[-0.483, 629.533, 1632.076]} scale={10} />
          <group position={[0, 2230.346, 1012.007]} scale={10}>
            <mesh geometry={nodes.red_02_red_0.geometry} material={materials.material} position={[0, -0.016, 0]} />
          </group>
          <group position={[-850.345, -1534.308, 367.18]} scale={10}>
            <mesh geometry={nodes.red_04_red_0.geometry} material={materials.material} position={[-0.001, 0, 0]} />
          </group>
          <group position={[850.345, -1534.307, 367.18]} scale={10}>
            <mesh geometry={nodes.red_05_red_0.geometry} material={materials.material} position={[0.001, 0, 0]} />
          </group>
          <mesh geometry={nodes.red_06_red_0.geometry} material={materials.material} position={[574.315, 2288.976, 729.816]} scale={10} />
          <mesh geometry={nodes.red_07_red_0.geometry} material={materials.material} position={[-568.63, 2289.897, 725.563]} scale={10} />
          <group position={[-0.073, 2315.017, 1021.958]} scale={10}>
            <mesh geometry={nodes.red_08_red_0.geometry} material={materials.material} position={[0.002, 0.006, 0]} />
          </group>
          <group position={[-850.345, 1259.283, 367.18]} scale={10}>
            <mesh geometry={nodes.red_10_red_0.geometry} material={materials.material} position={[-0.001, 0, 0]} />
          </group>
          <group position={[850.345, 1259.283, 367.18]} scale={10}>
            <mesh geometry={nodes.red_11_red_0.geometry} material={materials.material} position={[0.001, 0, 0]} />
          </group>
          <group position={[0.001, 634.393, 1631.053]} scale={10}>
            <mesh geometry={nodes.red_13_red_0.geometry} material={materials.material} position={[0, 0.026, 0.012]} />
          </group>
          <mesh geometry={nodes.red_14_red_0.geometry} material={materials.material} position={[-831.108, -857.495, 722.643]} scale={10} />
          <group position={[0.073, -2334.829, 902.885]} scale={10}>
            <mesh geometry={nodes.red_15_red_0.geometry} material={materials.material} position={[-0.002, 0, 0]} />
          </group>
          <group position={[0.001, -2201.886, 400.419]} scale={10}>
            <mesh geometry={nodes.red_16_red_0.geometry} material={materials.material} position={[0, 0.319, 0.22]} />
          </group>
          <mesh geometry={nodes.silver_01_silver_0.geometry} material={materials.silver} position={[868.88, -1534.625, 367.983]} scale={10} />
          <mesh geometry={nodes.silver_02_silver_0.geometry} material={materials.silver} position={[-868.879, -1534.625, 367.983]} scale={10} />
          <group position={[-73.455, 2316.866, 1114.521]} scale={10}>
            <mesh geometry={nodes.silver_03_silver_0.geometry} material={materials.silver} position={[-0.007, -0.031, 0.008]} />
          </group>
          <mesh geometry={nodes.silver_04_silver_0.geometry} material={materials.silver} position={[-868.879, 1258.966, 367.983]} scale={10} />
          <mesh geometry={nodes.silver_05_silver_0.geometry} material={materials.silver} position={[868.88, 1258.966, 367.983]} scale={10} />
          <mesh geometry={nodes.silver_06_silver_0.geometry} material={materials.silver} position={[-0.483, 618.518, 1632.076]} scale={10} />
          <group position={[0.035, -2118.247, 843.16]} scale={10}>
            <mesh geometry={nodes.silver_09_silver_0.geometry} material={materials.silver} position={[-0.002, -0.002, 0]} />
          </group>
          <group position={[772.371, 1382.626, 394.208]} scale={10}>
            <mesh geometry={nodes.silver_d_02_silver_d_0.geometry} material={materials.silver_d} position={[0, 0.115, 0.252]} />
          </group>
          <group position={[766.058, -1411.984, 392.783]} scale={10}>
            <mesh geometry={nodes.silver_d_04_silver_d_0.geometry} material={materials.silver_d} position={[0, 0.115, 0.252]} />
          </group>
          <group position={[0, 2306.37, 553.837]} scale={10}>
            <mesh geometry={nodes.silver_d_05_silver_d_0.geometry} material={materials.silver_d} position={[0, 0.079, -0.002]} />
          </group>
          <group position={[0, -2327.26, 850.023]} scale={10}>
            <mesh geometry={nodes.silver_d_06_silver_d_0.geometry} material={materials.silver_d} position={[0, -0.008, 0.007]} />
          </group>
          <group position={[0, -2302.355, 848.427]} scale={10}>
            <mesh geometry={nodes.silver_d_07_silver_d_0.geometry} material={materials.silver_d} position={[0, -0.07, -0.006]} />
          </group>
          <group position={[0, -2224.387, 581.018]} scale={10}>
            <mesh geometry={nodes.silver_d_08_silver_d_0.geometry} material={materials.silver_d} position={[0, -0.015, 0.008]} />
          </group>
          <mesh geometry={nodes.tire_05_tire_0.geometry} material={materials.tire} position={[-878.405, 1262.497, 369.421]} scale={10} />
          <group position={[744.913, -1531.097, 369.517]} scale={10}>
            <mesh geometry={nodes.tire_08_tire_0.geometry} material={materials.tire} position={[-0.064, 0, 0]} />
          </group>
          <group position={[-744.913, -1531.097, 369.517]} scale={10}>
            <mesh geometry={nodes.tire_09_tire_0.geometry} material={materials.tire} position={[0.064, 0, 0]} />
          </group>
          <group position={[-744.913, 1262.494, 369.517]} scale={10}>
            <mesh geometry={nodes.tire_10_tire_0.geometry} material={materials.tire} position={[0.064, 0, 0]} />
          </group>
          <group position={[744.913, 1262.494, 369.517]} scale={10}>
            <mesh geometry={nodes.tire_11_tire_0.geometry} material={materials.tire} position={[-0.064, 0, 0]} />
          </group>
          <mesh geometry={nodes.black_02_black_0.geometry} material={materials.black} position={[0, 52.65, 628.006]} scale={10} />
          <mesh geometry={nodes.black_08_black_0.geometry} material={materials.black} position={[0, -2162.675, 578.888]} scale={10} />
          <mesh geometry={nodes.black_10_black_0.geometry} material={materials.black} position={[5.547, -2128.08, 740.644]} scale={10} />
          <mesh geometry={nodes.black_matt_05_black_matt_0.geometry} material={materials.black_matt} position={[-801.056, 1385.876, 394.141]} scale={10} />
          <mesh geometry={nodes.black_matt_07_black_matt_0.geometry} material={materials.black_matt} position={[0, 2333.313, 674.749]} scale={10} />
          <mesh geometry={nodes.black_matt_10_black_matt_0.geometry} material={materials.black_matt} position={[0.818, 2220.511, 974.734]} scale={10} />
          <mesh geometry={nodes.black_matt_11_black_matt_0.geometry} material={materials.black_matt} position={[-8.595, 1260.961, 530.603]} scale={10} />
          <mesh geometry={nodes.black_matt_12_black_matt_0.geometry} material={materials.black_matt} position={[-8.593, 1260.961, 398.083]} scale={10} />
          <mesh geometry={nodes.black_matt_13_black_matt_0.geometry} material={materials.black_matt} position={[-8.595, -1602.882, 365.834]} scale={10} />
          <mesh geometry={nodes.black_matt_16_black_matt_0.geometry} material={materials.black_matt} position={[-8.595, -1555.945, 365.834]} scale={10} />
          <mesh geometry={nodes.black_matt_17_black_matt_0.geometry} material={materials.black_matt} position={[-8.595, -1537.235, 568.575]} scale={10} />
          <mesh geometry={nodes.black_matt_18_black_matt_0.geometry} material={materials.black_matt} position={[-8.593, -1537.235, 432.543]} scale={10} />
          <mesh geometry={nodes.black_matt_21_black_matt_0.geometry} material={materials.black_matt} position={[-739.389, -1532.116, 365.975]} scale={10} />
          <mesh geometry={nodes.black_matt_24_black_matt_0.geometry} material={materials.black_matt} position={[-761.723, -1420.639, 391.725]} scale={10} />
          <mesh geometry={nodes.black_matt_26_black_matt_0.geometry} material={materials.black_matt} position={[-794.746, -1408.735, 392.716]} scale={10} />
          <mesh geometry={nodes.black_matt_29_black_matt_0.geometry} material={materials.black_matt} position={[-100.005, -1278.516, 1204.72]} scale={10} />
          <mesh geometry={nodes.black_matt_30_black_matt_0.geometry} material={materials.black_matt} position={[477.536, -1237.757, 1201.469]} scale={10} />
          <mesh geometry={nodes.black_matt_35_black_matt_0.geometry} material={materials.black_matt} position={[-8.6, 943.293, 493.594]} scale={10} />
          <mesh geometry={nodes.black_matt_37_black_matt_0.geometry} material={materials.black_matt} position={[0, 1435.077, 738.84]} scale={10} />
          <mesh geometry={nodes.black_matt_38_black_matt_0.geometry} material={materials.black_matt} position={[-19.879, 1260.994, 365.834]} scale={10} />
          <mesh geometry={nodes.black_matt_39_black_matt_0.geometry} material={materials.black_matt} position={[-745.699, 1262.494, 367.401]} scale={10} />
          <mesh geometry={nodes.black_matt_42_black_matt_0.geometry} material={materials.black_matt} position={[-768.033, 1373.972, 393.15]} scale={10} />
          <mesh geometry={nodes.black_matt_47_black_matt_0.geometry} material={materials.black_matt} position={[169.132, 565.233, 427.388]} scale={10} />
          <mesh geometry={nodes.black_matt_49_black_matt_0.geometry} material={materials.black_matt} position={[-8.598, 706.721, 631.809]} scale={10} />
          <mesh geometry={nodes.black_matt_50_black_matt_0.geometry} material={materials.black_matt} position={[-8.597, 717.761, 396.135]} scale={10} />
          <mesh geometry={nodes.black_matt_52_black_matt_0.geometry} material={materials.black_matt} position={[0.06, 765.561, 925.796]} scale={10} />
          <mesh geometry={nodes.black_matt_53_black_matt_0.geometry} material={materials.black_matt} position={[250.919, -1162.651, 415.973]} scale={10} />
          <mesh geometry={nodes.black_matt_54_black_matt_0.geometry} material={materials.black_matt} position={[-8.6, -1042.379, 419.002]} scale={10} />
          <mesh geometry={nodes.black_matt_59_black_matt_0.geometry} material={materials.black_matt} position={[256.665, -1199.982, 1218.397]} scale={10} />
          <mesh geometry={nodes.black_matt_60_black_matt_0.geometry} material={materials.black_matt} position={[-311.129, -1197.169, 1214.131]} scale={10} />
          <mesh geometry={nodes.black_matt_63_black_matt_0.geometry} material={materials.black_matt} position={[0, 1428.521, 741.158]} scale={10} />
          <mesh geometry={nodes.black_matt_64_black_matt_0.geometry} material={materials.black_matt} position={[0, 1374.5, 981.353]} scale={10} />
          <mesh geometry={nodes.black_matt_72_black_matt_0.geometry} material={materials.black_matt} position={[53.533, -1817.602, 484.435]} scale={10} />
          <mesh geometry={nodes.black_matt_73_black_matt_0.geometry} material={materials.black_matt} position={[-8.595, -1736.294, 387.835]} scale={10} />
          <mesh geometry={nodes.black_matt_74_black_matt_0.geometry} material={materials.black_matt} position={[0.818, 753.718, 984.864]} scale={10} />
          <mesh geometry={nodes.black_matt_75_black_matt_0.geometry} material={materials.black_matt} position={[-8.599, -681.936, 392.846]} scale={10} />
          <mesh geometry={nodes.brakes1_01_brakes1_0.geometry} material={materials.brakes1} position={[-761.173, -1541.898, 365.898]} scale={10} />
          <mesh geometry={nodes.brakes1_03_brakes1_0.geometry} material={materials.brakes1} position={[-767.483, 1252.712, 367.323]} scale={10} />
          <mesh geometry={nodes.chrome_04_chrome_0.geometry} material={materials.chrome} position={[0, 2190.144, 1001.49]} scale={10} />
          <mesh geometry={nodes.chrome_09_chrome_0.geometry} material={materials.chrome} position={[-832.303, -1533.386, 366.491]} scale={10} />
          <mesh geometry={nodes.chrome_10_chrome_0.geometry} material={materials.chrome} position={[832.303, -1533.386, 366.491]} scale={10} />
          <mesh geometry={nodes.chrome_11_chrome_0.geometry} material={materials.chrome} position={[0, 2247.926, 998.464]} scale={10} />
          <mesh geometry={nodes.chrome_12_chrome_0.geometry} material={materials.chrome} position={[0, 2257.454, 998.545]} scale={10} />
          <mesh geometry={nodes.chrome_18_chrome_0.geometry} material={materials.chrome} position={[-832.303, 1260.204, 366.491]} scale={10} />
          <mesh geometry={nodes.chrome_19_chrome_0.geometry} material={materials.chrome} position={[832.303, 1260.204, 366.491]} scale={10} />
          <mesh geometry={nodes.chrome_21_chrome_0.geometry} material={materials.chrome} position={[-1.023, 633.397, 1629.485]} scale={10} />
          <mesh geometry={nodes.chrome_22_chrome_0.geometry} material={materials.chrome} position={[0, 634.866, 1641.19]} scale={10} />
          <mesh geometry={nodes.chrome_25_chrome_0.geometry} material={materials.chrome} position={[0, -788.823, 1247.775]} scale={10} />
          <mesh geometry={nodes.chrome_28_chrome_0.geometry} material={materials.chrome} position={[0, -2189.768, 929.469]} scale={10} />
          <mesh geometry={nodes.chrome_29_chrome_0.geometry} material={materials.chrome} position={[0, -2173.796, 585.281]} scale={10} />
          <mesh geometry={nodes.chrome_31_chrome_0.geometry} material={materials.chrome} position={[0, -2159.655, 930.252]} scale={10} />
          <mesh geometry={nodes.chrome_32_chrome_0.geometry} material={materials.chrome} position={[-0.444, -518.779, 1545.737]} scale={10} />
          <mesh geometry={nodes.d_glass_04_d_glass_0.geometry} material={materials.d_glass} position={[0, -2151.92, 931.413]} scale={10} />
          <mesh geometry={nodes.glass_02_glass_0.geometry} material={materials.glass} position={[0, 2207.47, 1001.49]} scale={10} />
          <mesh geometry={nodes.glass_04_glass_0.geometry} material={materials.glass} position={[0, 2265.252, 998.464]} scale={10} />
          <mesh geometry={nodes.glass_05_glass_0.geometry} material={materials.glass} position={[-96.274, 629.533, 1630.893]} scale={10} />
          <mesh geometry={nodes.glass_06_glass_0.geometry} material={materials.glass} position={[95.943, 629.533, 1630.893]} scale={10} />
          <mesh geometry={nodes.glass_07_glass_0.geometry} material={materials.glass} position={[0.001, 667.465, 1640.674]} scale={10} />
          <mesh geometry={nodes.interior_01_interior_0.geometry} material={materials.interior} position={[0.421, -10.882, 1099.89]} scale={10} />
          <mesh geometry={nodes.interior_02_interior_0.geometry} material={materials.interior} position={[0.957, -788.469, 958.355]} scale={10} />
          <mesh geometry={nodes.interior_03_interior_0.geometry} material={materials.interior} position={[0.417, -249.993, 906.847]} scale={10} />
          <mesh geometry={nodes.interior_05_interior_0.geometry} material={materials.interior} position={[317.129, -701.506, 1123.148]} scale={10} />
          <mesh geometry={nodes.interior_06_interior_0.geometry} material={materials.interior} position={[317.083, -599.157, 1182.976]} scale={10} />
          <mesh geometry={nodes.interior_07_interior_0.geometry} material={materials.interior} position={[0.408, -587.16, 1566.899]} scale={10} />
          <mesh geometry={nodes.interior_08_interior_0.geometry} material={materials.interior} position={[-0.626, -525.544, 1545.586]} scale={10} />
          <mesh geometry={nodes.orange_01_orange_0.geometry} material={materials.orange} position={[0, -2078.115, 934.681]} scale={10} />
          <mesh geometry={nodes.plate_02_plate_0.geometry} material={materials.plate} position={[0, -2428.611, 525.639]} scale={10} />
          <mesh geometry={nodes.r_glass_03_r_glass_0.geometry} material={materials.r_glass} position={[0.002, 647.234, 1641.271]} scale={10} />
          <mesh geometry={nodes.red_01_red_0.geometry} material={materials.material} position={[0, 2205.816, 1007.983]} scale={10} />
          <mesh geometry={nodes.red_03_red_0.geometry} material={materials.material} position={[0, 2230.866, 999.382]} scale={10} />
          <mesh geometry={nodes.red_09_red_0.geometry} material={materials.material} position={[831.121, -719.709, 722.314]} scale={10} />
          <mesh geometry={nodes.red_12_red_0.geometry} material={materials.material} position={[0.357, 633.397, 1629.485]} scale={10} />
          <mesh geometry={nodes.silver_07_silver_0.geometry} material={materials.silver} position={[95.943, 618.518, 1630.893]} scale={10} />
          <mesh geometry={nodes.silver_08_silver_0.geometry} material={materials.silver} position={[-96.274, 618.518, 1630.893]} scale={10} />
          <mesh geometry={nodes.silver_d_01_silver_d_0.geometry} material={materials.silver_d} position={[-772.371, 1382.626, 394.208]} scale={10} />
          <mesh geometry={nodes.silver_d_03_silver_d_0.geometry} material={materials.silver_d} position={[-766.061, -1411.984, 392.783]} scale={10} />
          <mesh geometry={nodes.tire_01_tire_0.geometry} material={materials.tire} position={[-747.27, -1531.096, 369.517]} scale={10} />
          <mesh geometry={nodes.tire_02_tire_0.geometry} material={materials.tire} position={[-878.405, -1531.094, 369.421]} scale={10} />
          <mesh geometry={nodes.tire_03_tire_0.geometry} material={materials.tire} position={[878.405, 1262.497, 369.421]} scale={10} />
          <mesh geometry={nodes.tire_04_tire_0.geometry} material={materials.tire} position={[747.27, 1262.494, 369.517]} scale={10} />
          <mesh geometry={nodes.tire_06_tire_0.geometry} material={materials.tire} position={[-747.27, 1262.494, 369.517]} scale={10} />
          <mesh geometry={nodes.tire_07_tire_0.geometry} material={materials.tire} position={[878.405, -1531.094, 369.421]} scale={10} />
          <mesh geometry={nodes.tire_12_tire_0.geometry} material={materials.tire} position={[747.27, -1531.096, 369.517]} scale={10} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Canyon.glb')
